<a href="https://colab.research.google.com/github/Tharunopi/PyTorch/blob/main/basics_pytorch.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [240]:
!nvidia-smi

/bin/bash: line 1: nvidia-smi: command not found


In [241]:
import torch
import numpy as np

**creating a scalar**



In [242]:
scalar = torch.tensor(3)

In [243]:
scalar.item() # return tensor back to int

3

In [244]:
scalar.ndim

0

**creating a vector**

In [245]:
vector = torch.tensor([7, 7])

In [246]:
vector.ndim

1

In [247]:
vector.shape

torch.Size([2])

**creating a MATRIX**

In [248]:
MATRIX = torch.tensor([[7, 8, 11],
                       [9, 10, 12]])
MATRIX

tensor([[ 7,  8, 11],
        [ 9, 10, 12]])

In [249]:
MATRIX.ndim

2

In [250]:
MATRIX.shape

torch.Size([2, 3])

In [251]:
MATRIX[1]

tensor([ 9, 10, 12])

**creating a TENSOR**

In [252]:
TENSOR = torch.tensor(
    [
        [
            [1, 2, 3],
            [4, 5, 6],
            [7, 8, 9]
        ]
    ]
)

In [253]:
TENSOR

tensor([[[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]])

In [254]:
TENSOR.ndim

3

In [255]:
TENSOR.shape

torch.Size([1, 3, 3])

**Random TENSOR**

In [256]:
RANDOM = torch.randint(0, 10, (5, 5), generator=torch.Generator(device='cpu'))

In [257]:
RANDOM

tensor([[0, 4, 7, 0, 9],
        [9, 4, 4, 9, 9],
        [6, 7, 7, 6, 2],
        [1, 8, 7, 6, 4],
        [2, 9, 5, 0, 0]])

In [258]:
# creating a image like tensor
image_tensor = torch.randint(0, 255, (224, 224, 3))

In [259]:
image_tensor.ndim

3

creating TENSORS with zeros and ones

In [260]:
# zeroes
z0 = torch.zeros(2, 3)
z0

tensor([[0., 0., 0.],
        [0., 0., 0.]])

In [261]:
# ones
o0 = torch.ones(2, 3)
o0

tensor([[1., 1., 1.],
        [1., 1., 1.]])

**creating range of tensors and torch-like**

In [262]:
rang = torch.arange(1, 11)

In [263]:
ten_zeros = torch.zeros_like(input = rang)
ten_zeros

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [264]:
d2 = torch.randint(0, 9, (5, 10))
o2 = torch.zeros_like(d2)
o2

tensor([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0, 0, 0, 0, 0]])

##**tensor datatypes**

In [265]:
test_tensor = torch.tensor([1, 2, 3],
                           dtype=torch.half,
                           requires_grad=False
                           )

In [266]:
float64_tensor = test_tensor.type(torch.double)
float64_tensor

tensor([1., 2., 3.], dtype=torch.float64)

In [267]:
test_tensor * float64_tensor

tensor([1., 4., 9.], dtype=torch.float64)

In [268]:
test_tensor.device

device(type='cpu')

In [269]:
image_tensor.device

device(type='cpu')

### **manipulating tensors**

In [270]:
mani_tensor = torch.tensor([[1, 2, 3],
                            [4, 5, 6]])

mani_tensor + 10

tensor([[11, 12, 13],
        [14, 15, 16]])

In [271]:
mani_tensor - 10

tensor([[-9, -8, -7],
        [-6, -5, -4]])

In [272]:
mani_tensor * 10

tensor([[10, 20, 30],
        [40, 50, 60]])

In [273]:
mani_tensor / 10

tensor([[0.1000, 0.2000, 0.3000],
        [0.4000, 0.5000, 0.6000]])

# **matrix multiplication**

In [274]:
# matrix multiplication by hand
%%time
a = [[1, 2, 3], [4, 5, 6]]
b = [[1, 2], [3, 4], [5, 6]]

a_cols = len(a[0])
a_rows = len(a)
b_cols = len(b[0])
b_rows = len(b)

result = [[0 for j in range(b_cols)] for i in range(a_rows)]

for i in range(a_rows):
  for j in range(b_cols):
    for k in range(a_cols):
      result[i][j] += a[i][k] * b[k][j]

CPU times: user 30 µs, sys: 0 ns, total: 30 µs
Wall time: 34.1 µs


In [275]:
# using pytorch matmul function

tensor_a = torch.tensor(a)
tensor_b = torch.tensor(b)


In [276]:
%%time
tensor_mul = torch.matmul(tensor_a, tensor_b)

CPU times: user 83 µs, sys: 4 µs, total: 87 µs
Wall time: 90.8 µs


In [277]:
%%time
tensor_a @ tensor_b

CPU times: user 77 µs, sys: 4 µs, total: 81 µs
Wall time: 84.4 µs


tensor([[22, 28],
        [49, 64]])

In [278]:
# checking rules to satisfy for matmul

def check(a:torch.tensor, b:torch.tensor):
  if a.shape[1] == b.T.shape[0]:
    return torch.matmul(a, b.T)
  if a.T.shape[1] == b.shape[0]:
    return torch.matmul(a.T, b)
  if a.T.shape[1] == b.T.shape[0]:
    return torch.matmul(a.T, b.T)
  if a.shape[1] != b.shape[0]:
    return print(f"Invalid shape {a.shape} @ {b.shape}")
  return torch.matmul(a, b)

check(torch.rand(3, 2), torch.rand(5, 3))

tensor([[0.5723, 0.8154, 0.4003, 0.7849, 0.5778],
        [0.3689, 0.6642, 0.3941, 0.7467, 0.5547]])

# **Tensor Aggregation**

In [279]:
tril = torch.randint(1, 983, (6, 6), dtype=torch.half)
tril

tensor([[221., 748., 980., 545., 764., 855.],
        [894., 871., 608., 193., 459., 120.],
        [ 83., 286., 458., 699., 835., 604.],
        [333., 696., 550., 881., 583., 623.],
        [  3., 922., 320., 473., 348., 503.],
        [632., 558., 608., 924., 356., 907.]], dtype=torch.float16)

In [280]:
#min
print(torch.min(tril), torch.argmin(tril))

tensor(3., dtype=torch.float16) tensor(24)


In [281]:
#max
print(torch.max(tril), torch.argmax(tril))

tensor(980., dtype=torch.float16) tensor(2)


In [282]:
#average
torch.mean(tril)

tensor(568., dtype=torch.float16)

In [283]:
#sum
torch.sum(tril)

tensor(20448., dtype=torch.float16)

# **Reshaping, View, Stack, Squeezing, Unsqueezing, Permute**

In [284]:
tensor = torch.arange(1, 11)
tensor

tensor([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [285]:
x = tensor.reshape(10, 1)

In [286]:
#change view
z = x.view(10, 1)
z [0, 0] = 99

In [287]:
print(x, z)

tensor([[99],
        [ 2],
        [ 3],
        [ 4],
        [ 5],
        [ 6],
        [ 7],
        [ 8],
        [ 9],
        [10]]) tensor([[99],
        [ 2],
        [ 3],
        [ 4],
        [ 5],
        [ 6],
        [ 7],
        [ 8],
        [ 9],
        [10]])


In [288]:
#stacking
a = torch.tensor([1, 2, 3])
b = torch.tensor([4, 5, 6])

In [289]:
torch.stack([a, b] )

tensor([[1, 2, 3],
        [4, 5, 6]])

In [290]:
torch.hstack([a, b])

tensor([1, 2, 3, 4, 5, 6])

In [291]:
torch.vstack([a, b])

tensor([[1, 2, 3],
        [4, 5, 6]])

In [292]:
# Squeezing a tensor

a = torch.zeros(2, 1, 2, 1, 2)
b = torch.squeeze(a)
print(a.size(), b.size())

torch.Size([2, 1, 2, 1, 2]) torch.Size([2, 2, 2])


In [293]:
print(x.shape, x)
print(torch.squeeze(x).shape, torch.squeeze(x))

torch.Size([10, 1]) tensor([[99],
        [ 2],
        [ 3],
        [ 4],
        [ 5],
        [ 6],
        [ 7],
        [ 8],
        [ 9],
        [10]])
torch.Size([10]) tensor([99,  2,  3,  4,  5,  6,  7,  8,  9, 10])


In [294]:
#Unsqueezing tensor
squeezed = torch.squeeze(x)
print(squeezed.shape, squeezed)
unsqueezed = torch.unsqueeze(squeezed, dim=1)
print(unsqueezed.shape, unsqueezed)

torch.Size([10]) tensor([99,  2,  3,  4,  5,  6,  7,  8,  9, 10])
torch.Size([10, 1]) tensor([[99],
        [ 2],
        [ 3],
        [ 4],
        [ 5],
        [ 6],
        [ 7],
        [ 8],
        [ 9],
        [10]])


In [295]:
#permuting -> changing the dimensions of the tensor it returns the view of the original tensor
new = torch.rand(size=(224, 224, 3))

permuted_new = torch.permute(new, (2, 0, 1))

In [296]:
permuted_new.size()

torch.Size([3, 224, 224])

In [297]:
new[0, 0, 0] = 6845

In [298]:
permuted_new[0, 0, 0]

tensor(6845.)

# **Indexing**

In [299]:
x = torch.arange(1, 241).reshape(1, 60, 4)
x.shape

torch.Size([1, 60, 4])

In [300]:
 x[0, :, 0]

tensor([  1,   5,   9,  13,  17,  21,  25,  29,  33,  37,  41,  45,  49,  53,
         57,  61,  65,  69,  73,  77,  81,  85,  89,  93,  97, 101, 105, 109,
        113, 117, 121, 125, 129, 133, 137, 141, 145, 149, 153, 157, 161, 165,
        169, 173, 177, 181, 185, 189, 193, 197, 201, 205, 209, 213, 217, 221,
        225, 229, 233, 237])

# **Pytorch tensor and Numpy**

In [301]:
# numpy to tensor
a = np.arange(1, 11)
tensor_a = torch.from_numpy(a)
print(tensor_a)

tensor([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])


In [302]:
#tensor to numpy
b = torch.arange(1, 11)
array_b = b.numpy()
print(array_b)

[ 1  2  3  4  5  6  7  8  9 10]


# **Reproducibility -> used to reduce the randomness across the device**

In [303]:
torch.manual_seed(42)
rand_a = torch.rand(3, 4)

torch.manual_seed(42)
rand_b = torch.rand(3, 4)

print(rand_a)
print(rand_b)
print(rand_a == rand_b)

tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])
tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])
tensor([[True, True, True, True],
        [True, True, True, True],
        [True, True, True, True]])


# **Running tensors and pytorch objects in GPU**

In [305]:
!nvidia-smi

/bin/bash: line 1: nvidia-smi: command not found


In [306]:
device = "cuda" if torch.cuda.is_available() else "cpu"

In [307]:
device

'cpu'

In [308]:
# unable to perform GPU and CPU operations because colab currently does not have any cpu online/avaliable

# **Exercises**

In [310]:
#Create a random tensor with shape (7, 7)

random_tensor = torch.rand(7, 7)
print(random_tensor)

tensor([[0.8694, 0.5677, 0.7411, 0.4294, 0.8854, 0.5739, 0.2666],
        [0.6274, 0.2696, 0.4414, 0.2969, 0.8317, 0.1053, 0.2695],
        [0.3588, 0.1994, 0.5472, 0.0062, 0.9516, 0.0753, 0.8860],
        [0.5832, 0.3376, 0.8090, 0.5779, 0.9040, 0.5547, 0.3423],
        [0.6343, 0.3644, 0.7104, 0.9464, 0.7890, 0.2814, 0.7886],
        [0.5895, 0.7539, 0.1952, 0.0050, 0.3068, 0.1165, 0.9103],
        [0.6440, 0.7071, 0.6581, 0.4913, 0.8913, 0.1447, 0.5315]])


In [311]:
#Perform a matrix multiplication on the tensor from 2 with another random tensor with shape (1, 7)
random_tensor_1 = torch.rand(1, 7).T
torch.matmul(random_tensor, random_tensor_1)

tensor([[1.9625],
        [1.0950],
        [0.9967],
        [1.8910],
        [1.9205],
        [1.0674],
        [1.6949]])