<a href="https://colab.research.google.com/github/Tharunopi/PyTorch/blob/main/basics_pytorch.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
!nvidia-smi

Thu Jan 23 02:50:04 2025       
+---------------------------------------------------------------------------------------+
| NVIDIA-SMI 535.104.05             Driver Version: 535.104.05   CUDA Version: 12.2     |
|-----------------------------------------+----------------------+----------------------+
| GPU  Name                 Persistence-M | Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |         Memory-Usage | GPU-Util  Compute M. |
|                                         |                      |               MIG M. |
|=========================================+======================+======================|
|   0  Tesla T4                       Off | 00000000:00:04.0 Off |                    0 |
| N/A   40C    P8               9W /  70W |      0MiB / 15360MiB |      0%      Default |
|                                         |                      |                  N/A |
+-----------------------------------------+----------------------+--

In [2]:
import torch

**creating a scalar**



In [3]:
scalar = torch.tensor(3)

In [4]:
scalar.item() # return tensor back to int

3

In [5]:
scalar.ndim

0

**creating a vector**

In [6]:
vector = torch.tensor([7, 7])

In [7]:
vector.ndim

1

In [8]:
vector.shape

torch.Size([2])

**creating a MATRIX**

In [9]:
MATRIX = torch.tensor([[7, 8, 11],
                       [9, 10, 12]])
MATRIX

tensor([[ 7,  8, 11],
        [ 9, 10, 12]])

In [10]:
MATRIX.ndim

2

In [11]:
MATRIX.shape

torch.Size([2, 3])

In [12]:
MATRIX[1]

tensor([ 9, 10, 12])

**creating a TENSOR**

In [13]:
TENSOR = torch.tensor(
    [
        [
            [1, 2, 3],
            [4, 5, 6],
            [7, 8, 9]
        ]
    ]
)

In [14]:
TENSOR

tensor([[[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]])

In [15]:
TENSOR.ndim

3

In [16]:
TENSOR.shape

torch.Size([1, 3, 3])

**Random TENSOR**

In [25]:
RANDOM = torch.randint(0, 10, (5, 5), generator=torch.Generator(device='cpu'))

In [26]:
RANDOM

tensor([[0, 4, 7, 0, 9],
        [9, 4, 4, 9, 9],
        [6, 7, 7, 6, 2],
        [1, 8, 7, 6, 4],
        [2, 9, 5, 0, 0]])

In [28]:
# creating a image like tensor
image_tensor = torch.randint(0, 255, (224, 224, 3))

In [33]:
image_tensor.ndim

3

creating TENSORS with zeros and ones

In [35]:
# zeroes
z0 = torch.zeros(2, 3)
z0

tensor([[0., 0., 0.],
        [0., 0., 0.]])

In [37]:
# ones
o0 = torch.ones(2, 3)
o0

tensor([[1., 1., 1.],
        [1., 1., 1.]])

**creating range of tensors and torch-like**

In [40]:
rang = torch.arange(1, 11)

In [41]:
ten_zeros = torch.zeros_like(input = rang)
ten_zeros

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [43]:
d2 = torch.randint(0, 9, (5, 10))
o2 = torch.zeros_like(d2)
o2

tensor([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0, 0, 0, 0, 0]])

##**tensor datatypes**

In [47]:
test_tensor = torch.tensor([1, 2, 3],
                           dtype=torch.half,
                           device='cuda',
                           requires_grad=False
                           )

In [48]:
float64_tensor = test_tensor.type(torch.double)
float64_tensor

tensor([1., 2., 3.], device='cuda:0', dtype=torch.float64)

In [49]:
test_tensor * float64_tensor

tensor([1., 4., 9.], device='cuda:0', dtype=torch.float64)

In [50]:
test_tensor.device

device(type='cuda', index=0)

In [51]:
image_tensor.device

device(type='cpu')

### **manipulating tensors**

In [52]:
mani_tensor = torch.tensor([[1, 2, 3],
                            [4, 5, 6]])

mani_tensor + 10

tensor([[11, 12, 13],
        [14, 15, 16]])

In [53]:
mani_tensor - 10

tensor([[-9, -8, -7],
        [-6, -5, -4]])

In [54]:
mani_tensor * 10

tensor([[10, 20, 30],
        [40, 50, 60]])

In [55]:
mani_tensor / 10

tensor([[0.1000, 0.2000, 0.3000],
        [0.4000, 0.5000, 0.6000]])

**matrix multiplication **

In [77]:
# matrix multiplication by hand

a = [[1, 2, 3], [4, 5, 6]]
b = [[1, 2], [3, 4], [5, 6]]

a_cols = len(a[0])
a_rows = len(a)
b_cols = len(b[0])
b_rows = len(b)

result = [[0 for j in range(b_cols)] for i in range(a_rows)]

for i in range(a_rows):
  for j in range(b_cols):
    for k in range(a_cols):
      result[i][j] += a[i][k] * b[k][j]

In [78]:
result

[[22, 28], [49, 64]]