<a href="https://colab.research.google.com/github/Tharunopi/PyTorch/blob/main/basics_pytorch.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
!nvidia-smi

/bin/bash: line 1: nvidia-smi: command not found


In [2]:
import torch
import numpy as np

**creating a scalar**



In [3]:
scalar = torch.tensor(3)

In [4]:
scalar.item() # return tensor back to int

3

In [5]:
scalar.ndim

0

**creating a vector**

In [6]:
vector = torch.tensor([7, 7])

In [7]:
vector.ndim

1

In [8]:
vector.shape

torch.Size([2])

**creating a MATRIX**

In [9]:
MATRIX = torch.tensor([[7, 8, 11],
                       [9, 10, 12]])
MATRIX

tensor([[ 7,  8, 11],
        [ 9, 10, 12]])

In [10]:
MATRIX.ndim

2

In [11]:
MATRIX.shape

torch.Size([2, 3])

In [12]:
MATRIX[1]

tensor([ 9, 10, 12])

**creating a TENSOR**

In [13]:
TENSOR = torch.tensor(
    [
        [
            [1, 2, 3],
            [4, 5, 6],
            [7, 8, 9]
        ]
    ]
)

In [14]:
TENSOR

tensor([[[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]])

In [15]:
TENSOR.ndim

3

In [16]:
TENSOR.shape

torch.Size([1, 3, 3])

**Random TENSOR**

In [17]:
RANDOM = torch.randint(0, 10, (5, 5), generator=torch.Generator(device='cpu'))

In [18]:
RANDOM

tensor([[0, 4, 7, 0, 9],
        [9, 4, 4, 9, 9],
        [6, 7, 7, 6, 2],
        [1, 8, 7, 6, 4],
        [2, 9, 5, 0, 0]])

In [19]:
# creating a image like tensor
image_tensor = torch.randint(0, 255, (224, 224, 3))

In [20]:
image_tensor.ndim

3

creating TENSORS with zeros and ones

In [21]:
# zeroes
z0 = torch.zeros(2, 3)
z0

tensor([[0., 0., 0.],
        [0., 0., 0.]])

In [22]:
# ones
o0 = torch.ones(2, 3)
o0

tensor([[1., 1., 1.],
        [1., 1., 1.]])

**creating range of tensors and torch-like**

In [23]:
rang = torch.arange(1, 11)

In [24]:
ten_zeros = torch.zeros_like(input = rang)
ten_zeros

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [25]:
d2 = torch.randint(0, 9, (5, 10))
o2 = torch.zeros_like(d2)
o2

tensor([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0, 0, 0, 0, 0]])

##**tensor datatypes**

In [26]:
test_tensor = torch.tensor([1, 2, 3],
                           dtype=torch.half,
                           requires_grad=False
                           )

In [27]:
float64_tensor = test_tensor.type(torch.double)
float64_tensor

tensor([1., 2., 3.], dtype=torch.float64)

In [28]:
test_tensor * float64_tensor

tensor([1., 4., 9.], dtype=torch.float64)

In [29]:
test_tensor.device

device(type='cpu')

In [30]:
image_tensor.device

device(type='cpu')

### **manipulating tensors**

In [31]:
mani_tensor = torch.tensor([[1, 2, 3],
                            [4, 5, 6]])

mani_tensor + 10

tensor([[11, 12, 13],
        [14, 15, 16]])

In [32]:
mani_tensor - 10

tensor([[-9, -8, -7],
        [-6, -5, -4]])

In [33]:
mani_tensor * 10

tensor([[10, 20, 30],
        [40, 50, 60]])

In [34]:
mani_tensor / 10

tensor([[0.1000, 0.2000, 0.3000],
        [0.4000, 0.5000, 0.6000]])

# **matrix multiplication**

In [35]:
# matrix multiplication by hand
%%time
a = [[1, 2, 3], [4, 5, 6]]
b = [[1, 2], [3, 4], [5, 6]]

a_cols = len(a[0])
a_rows = len(a)
b_cols = len(b[0])
b_rows = len(b)

result = [[0 for j in range(b_cols)] for i in range(a_rows)]

for i in range(a_rows):
  for j in range(b_cols):
    for k in range(a_cols):
      result[i][j] += a[i][k] * b[k][j]

CPU times: user 24 µs, sys: 5 µs, total: 29 µs
Wall time: 33.6 µs


In [36]:
# using pytorch matmul function

tensor_a = torch.tensor(a)
tensor_b = torch.tensor(b)


In [37]:
%%time
tensor_mul = torch.matmul(tensor_a, tensor_b)

CPU times: user 1.68 ms, sys: 118 µs, total: 1.8 ms
Wall time: 7.03 ms


In [38]:
%%time
tensor_a @ tensor_b

CPU times: user 988 µs, sys: 0 ns, total: 988 µs
Wall time: 932 µs


tensor([[22, 28],
        [49, 64]])

In [39]:
# checking rules to satisfy for matmul

def check(a:torch.tensor, b:torch.tensor):
  if a.shape[1] == b.T.shape[0]:
    return torch.matmul(a, b.T)
  if a.T.shape[1] == b.shape[0]:
    return torch.matmul(a.T, b)
  if a.T.shape[1] == b.T.shape[0]:
    return torch.matmul(a.T, b.T)
  if a.shape[1] != b.shape[0]:
    return print(f"Invalid shape {a.shape} @ {b.shape}")
  return torch.matmul(a, b)

check(torch.rand(3, 2), torch.rand(5, 3))

tensor([[0.9949, 1.2188, 1.3001, 1.2328, 1.6667],
        [1.0500, 1.4169, 1.5606, 1.2916, 1.6942]])

# **Tensor Aggregation**

In [40]:
tril = torch.randint(1, 983, (6, 6), dtype=torch.half)
tril

tensor([[603., 585., 439., 637., 546., 220.],
        [360., 419., 778., 486., 118., 235.],
        [ 29., 134., 425., 710., 559., 723.],
        [562.,  46., 616., 184., 252., 123.],
        [689., 675., 862., 417., 884., 387.],
        [662., 426., 444., 321., 333., 139.]], dtype=torch.float16)

In [41]:
#min
print(torch.min(tril), torch.argmin(tril))

tensor(29., dtype=torch.float16) tensor(12)


In [42]:
#max
print(torch.max(tril), torch.argmax(tril))

tensor(884., dtype=torch.float16) tensor(28)


In [43]:
#average
torch.mean(tril)

tensor(445.2500, dtype=torch.float16)

In [44]:
#sum
torch.sum(tril)

tensor(16032., dtype=torch.float16)

# **Reshaping, View, Stack, Squeezing, Unsqueezing, Permute**

In [45]:
tensor = torch.arange(1, 11)
tensor

tensor([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [46]:
x = tensor.reshape(10, 1)

In [47]:
#change view
z = x.view(10, 1)
z [0, 0] = 99

In [48]:
print(x, z)

tensor([[99],
        [ 2],
        [ 3],
        [ 4],
        [ 5],
        [ 6],
        [ 7],
        [ 8],
        [ 9],
        [10]]) tensor([[99],
        [ 2],
        [ 3],
        [ 4],
        [ 5],
        [ 6],
        [ 7],
        [ 8],
        [ 9],
        [10]])


In [49]:
#stacking
a = torch.tensor([1, 2, 3])
b = torch.tensor([4, 5, 6])

In [50]:
torch.stack([a, b] )

tensor([[1, 2, 3],
        [4, 5, 6]])

In [51]:
torch.hstack([a, b])

tensor([1, 2, 3, 4, 5, 6])

In [52]:
torch.vstack([a, b])

tensor([[1, 2, 3],
        [4, 5, 6]])

In [53]:
# Squeezing a tensor

a = torch.zeros(2, 1, 2, 1, 2)
b = torch.squeeze(a)
print(a.size(), b.size())

torch.Size([2, 1, 2, 1, 2]) torch.Size([2, 2, 2])


In [54]:
print(x.shape, x)
print(torch.squeeze(x).shape, torch.squeeze(x))

torch.Size([10, 1]) tensor([[99],
        [ 2],
        [ 3],
        [ 4],
        [ 5],
        [ 6],
        [ 7],
        [ 8],
        [ 9],
        [10]])
torch.Size([10]) tensor([99,  2,  3,  4,  5,  6,  7,  8,  9, 10])


In [55]:
#Unsqueezing tensor
squeezed = torch.squeeze(x)
print(squeezed.shape, squeezed)
unsqueezed = torch.unsqueeze(squeezed, dim=1)
print(unsqueezed.shape, unsqueezed)

torch.Size([10]) tensor([99,  2,  3,  4,  5,  6,  7,  8,  9, 10])
torch.Size([10, 1]) tensor([[99],
        [ 2],
        [ 3],
        [ 4],
        [ 5],
        [ 6],
        [ 7],
        [ 8],
        [ 9],
        [10]])


In [56]:
#permuting -> changing the dimensions of the tensor it returns the view of the original tensor
new = torch.rand(size=(224, 224, 3))

permuted_new = torch.permute(new, (2, 0, 1))

In [57]:
permuted_new.size()

torch.Size([3, 224, 224])

In [58]:
new[0, 0, 0] = 6845

In [59]:
permuted_new[0, 0, 0]

tensor(6845.)

# **Indexing**

In [60]:
x = torch.arange(1, 241).reshape(1, 60, 4)
x.shape

torch.Size([1, 60, 4])

In [61]:
 x[0, :, 0]

tensor([  1,   5,   9,  13,  17,  21,  25,  29,  33,  37,  41,  45,  49,  53,
         57,  61,  65,  69,  73,  77,  81,  85,  89,  93,  97, 101, 105, 109,
        113, 117, 121, 125, 129, 133, 137, 141, 145, 149, 153, 157, 161, 165,
        169, 173, 177, 181, 185, 189, 193, 197, 201, 205, 209, 213, 217, 221,
        225, 229, 233, 237])

# **Pytorch tensor and Numpy**

In [62]:
# numpy to tensor
a = np.arange(1, 11)
tensor_a = torch.from_numpy(a)
print(tensor_a)

tensor([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])


In [63]:
#tensor to numpy
b = torch.arange(1, 11)
array_b = b.numpy()
print(array_b)

[ 1  2  3  4  5  6  7  8  9 10]


# **Reproducibility -> used to reduce the randomness across the device**

In [64]:
torch.manual_seed(42)
rand_a = torch.rand(3, 4)

torch.manual_seed(42)
rand_b = torch.rand(3, 4)

print(rand_a)
print(rand_b)
print(rand_a == rand_b)

tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])
tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])
tensor([[True, True, True, True],
        [True, True, True, True],
        [True, True, True, True]])


# **Running tensors and pytorch objects in GPU**

In [65]:
!nvidia-smi

/bin/bash: line 1: nvidia-smi: command not found


In [66]:
device = "cuda" if torch.cuda.is_available() else "cpu"

In [67]:
device

'cpu'

In [68]:
# unable to perform GPU and CPU operations because colab currently does not have any cpu online/avaliable

# **Exercises**

In [69]:
#Create a random tensor with shape (7, 7)

random_tensor = torch.rand(7, 7)
print(random_tensor)

tensor([[0.8694, 0.5677, 0.7411, 0.4294, 0.8854, 0.5739, 0.2666],
        [0.6274, 0.2696, 0.4414, 0.2969, 0.8317, 0.1053, 0.2695],
        [0.3588, 0.1994, 0.5472, 0.0062, 0.9516, 0.0753, 0.8860],
        [0.5832, 0.3376, 0.8090, 0.5779, 0.9040, 0.5547, 0.3423],
        [0.6343, 0.3644, 0.7104, 0.9464, 0.7890, 0.2814, 0.7886],
        [0.5895, 0.7539, 0.1952, 0.0050, 0.3068, 0.1165, 0.9103],
        [0.6440, 0.7071, 0.6581, 0.4913, 0.8913, 0.1447, 0.5315]])


In [70]:
#Perform a matrix multiplication on the tensor from 2 with another random tensor with shape (1, 7)
random_tensor_1 = torch.rand(1, 7).T
torch.matmul(random_tensor, random_tensor_1)

tensor([[1.9625],
        [1.0950],
        [0.9967],
        [1.8910],
        [1.9205],
        [1.0674],
        [1.6949]])

In [71]:
# Set the random seed to 0 and do exercises 2 & 3 over again.
torch.manual_seed(0)
rt_1 = torch.rand(7, 7)
torch.manual_seed(0)
rt_2 = torch.rand(1, 7).T
torch.matmul(rt_1, rt_2)

tensor([[1.5985],
        [1.1173],
        [1.2741],
        [1.6838],
        [0.8279],
        [1.0347],
        [1.2498]])

In [74]:
#Create two random tensors of shape (2, 3) and send them both to the GPU (you'll need access to a GPU for this). Set torch.manual_seed(1234) when creating the tensors (this doesn't have to be the GPU random seed).
torch.manual_seed(1234)
rt_1 = torch.rand(2, 3)
torch.manual_seed(1234)
rt_2 = torch.rand(2, 3).T
resu = torch.matmul(rt_1, rt_2)

#Find the maximum and minimum values of the output
print(torch.min(resu))
print(torch.max(resu))

#Find the maximum and minimum index values of the output of 7.
print(torch.argmin(resu))
print(torch.argmax(resu))

tensor(0.2161)
tensor(0.6287)
tensor(1)
tensor(3)


In [77]:
# Make a random tensor with shape (1, 1, 1, 10) and then create a new tensor with all the 1 dimensions removed to be left with a tensor of shape (10).
# Set the seed to 7 when you create it and print out the first tensor and it's shape as well as the second tensor and it's shape.

torch.manual_seed(7)
random_tensor = torch.rand(1, 1, 1, 10)
print(random_tensor.shape)
new_tensor = torch.squeeze(random_tensor)
print(new_tensor.shape)

torch.Size([1, 1, 1, 10])
torch.Size([10])
