<a href="https://colab.research.google.com/github/Tharunopi/PyTorch/blob/main/basics_pytorch.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [105]:
!nvidia-smi

/bin/bash: line 1: nvidia-smi: command not found


In [106]:
import torch

**creating a scalar**



In [107]:
scalar = torch.tensor(3)

In [108]:
scalar.item() # return tensor back to int

3

In [109]:
scalar.ndim

0

**creating a vector**

In [110]:
vector = torch.tensor([7, 7])

In [111]:
vector.ndim

1

In [112]:
vector.shape

torch.Size([2])

**creating a MATRIX**

In [113]:
MATRIX = torch.tensor([[7, 8, 11],
                       [9, 10, 12]])
MATRIX

tensor([[ 7,  8, 11],
        [ 9, 10, 12]])

In [114]:
MATRIX.ndim

2

In [115]:
MATRIX.shape

torch.Size([2, 3])

In [116]:
MATRIX[1]

tensor([ 9, 10, 12])

**creating a TENSOR**

In [117]:
TENSOR = torch.tensor(
    [
        [
            [1, 2, 3],
            [4, 5, 6],
            [7, 8, 9]
        ]
    ]
)

In [118]:
TENSOR

tensor([[[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]])

In [119]:
TENSOR.ndim

3

In [120]:
TENSOR.shape

torch.Size([1, 3, 3])

**Random TENSOR**

In [121]:
RANDOM = torch.randint(0, 10, (5, 5), generator=torch.Generator(device='cpu'))

In [122]:
RANDOM

tensor([[0, 4, 7, 0, 9],
        [9, 4, 4, 9, 9],
        [6, 7, 7, 6, 2],
        [1, 8, 7, 6, 4],
        [2, 9, 5, 0, 0]])

In [123]:
# creating a image like tensor
image_tensor = torch.randint(0, 255, (224, 224, 3))

In [124]:
image_tensor.ndim

3

creating TENSORS with zeros and ones

In [125]:
# zeroes
z0 = torch.zeros(2, 3)
z0

tensor([[0., 0., 0.],
        [0., 0., 0.]])

In [126]:
# ones
o0 = torch.ones(2, 3)
o0

tensor([[1., 1., 1.],
        [1., 1., 1.]])

**creating range of tensors and torch-like**

In [127]:
rang = torch.arange(1, 11)

In [128]:
ten_zeros = torch.zeros_like(input = rang)
ten_zeros

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [129]:
d2 = torch.randint(0, 9, (5, 10))
o2 = torch.zeros_like(d2)
o2

tensor([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0, 0, 0, 0, 0]])

##**tensor datatypes**

In [130]:
test_tensor = torch.tensor([1, 2, 3],
                           dtype=torch.half,
                           requires_grad=False
                           )

In [131]:
float64_tensor = test_tensor.type(torch.double)
float64_tensor

tensor([1., 2., 3.], dtype=torch.float64)

In [132]:
test_tensor * float64_tensor

tensor([1., 4., 9.], dtype=torch.float64)

In [133]:
test_tensor.device

device(type='cpu')

In [134]:
image_tensor.device

device(type='cpu')

### **manipulating tensors**

In [135]:
mani_tensor = torch.tensor([[1, 2, 3],
                            [4, 5, 6]])

mani_tensor + 10

tensor([[11, 12, 13],
        [14, 15, 16]])

In [136]:
mani_tensor - 10

tensor([[-9, -8, -7],
        [-6, -5, -4]])

In [137]:
mani_tensor * 10

tensor([[10, 20, 30],
        [40, 50, 60]])

In [138]:
mani_tensor / 10

tensor([[0.1000, 0.2000, 0.3000],
        [0.4000, 0.5000, 0.6000]])

# **matrix multiplication**

In [139]:
# matrix multiplication by hand
%%time
a = [[1, 2, 3], [4, 5, 6]]
b = [[1, 2], [3, 4], [5, 6]]

a_cols = len(a[0])
a_rows = len(a)
b_cols = len(b[0])
b_rows = len(b)

result = [[0 for j in range(b_cols)] for i in range(a_rows)]

for i in range(a_rows):
  for j in range(b_cols):
    for k in range(a_cols):
      result[i][j] += a[i][k] * b[k][j]

CPU times: user 28 µs, sys: 0 ns, total: 28 µs
Wall time: 43.9 µs


In [140]:
# using pytorch matmul function

tensor_a = torch.tensor(a)
tensor_b = torch.tensor(b)


In [141]:
%%time
tensor_mul = torch.matmul(tensor_a, tensor_b)

CPU times: user 329 µs, sys: 0 ns, total: 329 µs
Wall time: 338 µs


In [142]:
%%time
tensor_a @ tensor_b

CPU times: user 174 µs, sys: 0 ns, total: 174 µs
Wall time: 127 µs


tensor([[22, 28],
        [49, 64]])

In [143]:
# checking rules to satisfy for matmul

def check(a:torch.tensor, b:torch.tensor):
  if a.shape[1] == b.T.shape[0]:
    return torch.matmul(a, b.T)
  if a.T.shape[1] == b.shape[0]:
    return torch.matmul(a.T, b)
  if a.T.shape[1] == b.T.shape[0]:
    return torch.matmul(a.T, b.T)
  if a.shape[1] != b.shape[0]:
    return print(f"Invalid shape {a.shape} @ {b.shape}")
  return torch.matmul(a, b)

check(torch.rand(3, 2), torch.rand(5, 3))

tensor([[1.0173, 0.5739, 0.7382, 0.3266, 0.3989],
        [1.3555, 0.6580, 0.7225, 0.7638, 0.7585]])

# **Tensor Aggregation**

In [144]:
tril = torch.randint(1, 983, (6, 6), dtype=torch.half)
tril

tensor([[ 56.,  56., 722., 280., 607., 298.],
        [879., 655., 203., 197.,  90., 598.],
        [544., 611.,  83., 390., 797., 538.],
        [ 73., 117.,  71., 637.,  81., 207.],
        [115., 880., 828., 215., 912.,  70.],
        [606., 250.,  29., 799., 343., 146.]], dtype=torch.float16)

In [145]:
#min
print(torch.min(tril), torch.argmin(tril))

tensor(29., dtype=torch.float16) tensor(32)


In [146]:
#max
print(torch.max(tril), torch.argmax(tril))

tensor(912., dtype=torch.float16) tensor(28)


In [147]:
#average
torch.mean(tril)

tensor(388.5000, dtype=torch.float16)

In [148]:
#sum
torch.sum(tril)

tensor(13984., dtype=torch.float16)

# **Reshaping, View, Stack, Squeezing, Unsqueezing, Permute**

In [149]:
tensor = torch.arange(1, 11)
tensor

tensor([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [150]:
x = tensor.reshape(10, 1)

In [151]:
#change view
z = x.view(10, 1)
z [0, 0] = 99

In [152]:
print(x, z)

tensor([[99],
        [ 2],
        [ 3],
        [ 4],
        [ 5],
        [ 6],
        [ 7],
        [ 8],
        [ 9],
        [10]]) tensor([[99],
        [ 2],
        [ 3],
        [ 4],
        [ 5],
        [ 6],
        [ 7],
        [ 8],
        [ 9],
        [10]])


In [153]:
#stacking
a = torch.tensor([1, 2, 3])
b = torch.tensor([4, 5, 6])

In [154]:
torch.stack([a, b] )

tensor([[1, 2, 3],
        [4, 5, 6]])

In [155]:
torch.hstack([a, b])

tensor([1, 2, 3, 4, 5, 6])

In [156]:
torch.vstack([a, b])

tensor([[1, 2, 3],
        [4, 5, 6]])

In [157]:
# Squeezing a tensor

a = torch.zeros(2, 1, 2, 1, 2)
b = torch.squeeze(a)
print(a.size(), b.size())

torch.Size([2, 1, 2, 1, 2]) torch.Size([2, 2, 2])


In [158]:
print(x.shape, x)
print(torch.squeeze(x).shape, torch.squeeze(x))

torch.Size([10, 1]) tensor([[99],
        [ 2],
        [ 3],
        [ 4],
        [ 5],
        [ 6],
        [ 7],
        [ 8],
        [ 9],
        [10]])
torch.Size([10]) tensor([99,  2,  3,  4,  5,  6,  7,  8,  9, 10])


In [159]:
#Unsqueezing tensor
squeezed = torch.squeeze(x)
print(squeezed.shape, squeezed)
unsqueezed = torch.unsqueeze(squeezed, dim=1)
print(unsqueezed.shape, unsqueezed)

torch.Size([10]) tensor([99,  2,  3,  4,  5,  6,  7,  8,  9, 10])
torch.Size([10, 1]) tensor([[99],
        [ 2],
        [ 3],
        [ 4],
        [ 5],
        [ 6],
        [ 7],
        [ 8],
        [ 9],
        [10]])


In [160]:
#permuting -> changing the dimensions of the tensor it returns the view of the original tensor
new = torch.rand(size=(224, 224, 3))

permuted_new = torch.permute(new, (2, 0, 1))

In [161]:
permuted_new.size()

torch.Size([3, 224, 224])

In [162]:
new[0, 0, 0] = 6845

In [163]:
permuted_new[0, 0, 0]

tensor(6845.)

# **Indexing**

In [164]:
x = torch.arange(1, 241).reshape(1, 60, 4)
x.shape

torch.Size([1, 60, 4])

In [166]:
 x[0, :, 0]

tensor([  1,   5,   9,  13,  17,  21,  25,  29,  33,  37,  41,  45,  49,  53,
         57,  61,  65,  69,  73,  77,  81,  85,  89,  93,  97, 101, 105, 109,
        113, 117, 121, 125, 129, 133, 137, 141, 145, 149, 153, 157, 161, 165,
        169, 173, 177, 181, 185, 189, 193, 197, 201, 205, 209, 213, 217, 221,
        225, 229, 233, 237])