In [12]:
!nvidia-smi

Tue Jan 21 14:49:45 2025       
+---------------------------------------------------------------------------------------+
| NVIDIA-SMI 535.104.05             Driver Version: 535.104.05   CUDA Version: 12.2     |
|-----------------------------------------+----------------------+----------------------+
| GPU  Name                 Persistence-M | Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |         Memory-Usage | GPU-Util  Compute M. |
|                                         |                      |               MIG M. |
|=========================================+======================+======================|
|   0  Tesla T4                       Off | 00000000:00:04.0 Off |                    0 |
| N/A   38C    P8               9W /  70W |      0MiB / 15360MiB |      0%      Default |
|                                         |                      |                  N/A |
+-----------------------------------------+----------------------+--

In [13]:
import torch

**creating a scalar**



In [24]:
scalar = torch.tensor(3)

In [28]:
scalar.item() # return tensor back to int

3

In [29]:
scalar.ndim

0

**creating a vector**

In [32]:
vector = torch.tensor([7, 7])

In [33]:
vector.ndim

1

In [38]:
vector.shape

torch.Size([2])

**creating a MATRIX**

In [42]:
MATRIX = torch.tensor([[7, 8, 11],
                       [9, 10, 12]])
MATRIX

tensor([[ 7,  8, 11],
        [ 9, 10, 12]])

In [43]:
MATRIX.ndim

2

In [44]:
MATRIX.shape

torch.Size([2, 3])

In [45]:
MATRIX[1]

tensor([ 9, 10, 12])

**creating a TENSOR**

In [49]:
TENSOR = torch.tensor(
    [
        [
            [1, 2, 3],
            [4, 5, 6],
            [7, 8, 9]
        ]
    ]
)

In [50]:
TENSOR

tensor([[[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]])

In [51]:
TENSOR.ndim

3

In [52]:
TENSOR.shape

torch.Size([1, 3, 3])