In [1]:
import torch
import numpy as np

From data

In [2]:
data = [[1, 2], [3, 4]]
x_data = torch.tensor(data)
x_data

tensor([[1, 2],
        [3, 4]])

From numpy array

In [3]:
np_array = np.array([[1, 2], [3, 4]])
x_np = torch.from_numpy(np_array)
x_np

tensor([[1, 2],
        [3, 4]], dtype=torch.int32)

From another tensor

In [5]:
x_ones = torch.ones_like(x_data)
x_rand = torch.rand_like(x_data, dtype=torch.float)
print(x_ones)
print(x_rand)

tensor([[1, 1],
        [1, 1]])
tensor([[0.4300, 0.9539],
        [0.1301, 0.1974]])


With random or constant values 

In [9]:
ones = torch.ones((2, 3))
ones.shape

torch.Size([2, 3])